my_nyc_parking_violations:
  outputs:
   dev:
     type: duckdb
     path: '../data/nyc_parking_violations.db'
   prod:
     type: duckdb
     # note that path is slightly different as GitHub actions
     # start in the root directory and not in the
     # nyc_parking_violations directory
     # We found a typo! Below was single dot
     path: '../data/prod_nyc_parking_violations.db'  
  target: dev
